name: Test & Build

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Build & Test > Next Template
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_API_KEY }}
      NEXT_PUBLIC_INFURA_API_KEY: ${{ secrets.NEXT_PUBLIC_INFURA_API_KEY }}
      I18NEXUS_PRE_BUILD: "true"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.5
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
        # env:
        #   I18NEXUS_API_KEY: ${{ secrets.I18NEXUS_API_KEY }}
      - name: Build
        run: pnpm run build
